"""Adicionar colunas sessao_aberta e sessao_expiracao

Revision ID: f028793ac9fa
Revises: 13b8e371b9eb
Create Date: 2023-06-06 00:37:34.605319

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f028793ac9fa'
down_revision = '13b8e371b9eb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.add_column('agendas', sa.Column('sessao_aberta', sa.Boolean, default=False))
    op.add_column('agendas', sa.Column('sessao_expiracao', sa.DateTime))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agendas',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('agendas_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('associate_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['associate_id'], ['associates.id'], name='agendas_associate_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='agendas_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('associates',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('associates_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='associates_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('votes',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('associate_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('agenda_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('vote', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['agenda_id'], ['agendas.id'], name='votes_agenda_id_fkey'),
    sa.ForeignKeyConstraint(['associate_id'], ['associates.id'], name='votes_associate_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='votes_pkey')
    )
    # ### end Alembic commands ###
